// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backchannel.proto

#ifndef PROTOBUF_backchannel_2eproto__INCLUDED
#define PROTOBUF_backchannel_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class Backchannel;
class BackchannelDefaultTypeInternal;
extern BackchannelDefaultTypeInternal _Backchannel_default_instance_;

namespace protobuf_backchannel_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_backchannel_2eproto

enum Backchannel_MsgType {
  Backchannel_MsgType_LOG = 0,
  Backchannel_MsgType_ERROR = 1
};
bool Backchannel_MsgType_IsValid(int value);
const Backchannel_MsgType Backchannel_MsgType_MsgType_MIN = Backchannel_MsgType_LOG;
const Backchannel_MsgType Backchannel_MsgType_MsgType_MAX = Backchannel_MsgType_ERROR;
const int Backchannel_MsgType_MsgType_ARRAYSIZE = Backchannel_MsgType_MsgType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Backchannel_MsgType_descriptor();
inline const ::std::string& Backchannel_MsgType_Name(Backchannel_MsgType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Backchannel_MsgType_descriptor(), value);
}
inline bool Backchannel_MsgType_Parse(
    const ::std::string& name, Backchannel_MsgType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Backchannel_MsgType>(
    Backchannel_MsgType_descriptor(), name, value);
}
// ===================================================================

class Backchannel : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Backchannel) */ {
 public:
  Backchannel();
  virtual ~Backchannel();

  Backchannel(const Backchannel& from);

  inline Backchannel& operator=(const Backchannel& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Backchannel& default_instance();

  static inline const Backchannel* internal_default_instance() {
    return reinterpret_cast<const Backchannel*>(
               &_Backchannel_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Backchannel* other);

  // implements Message ----------------------------------------------

  inline Backchannel* New() const PROTOBUF_FINAL { return New(NULL); }

  Backchannel* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Backchannel& from);
  void MergeFrom(const Backchannel& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Backchannel* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Backchannel_MsgType MsgType;
  static const MsgType LOG =
    Backchannel_MsgType_LOG;
  static const MsgType ERROR =
    Backchannel_MsgType_ERROR;
  static inline bool MsgType_IsValid(int value) {
    return Backchannel_MsgType_IsValid(value);
  }
  static const MsgType MsgType_MIN =
    Backchannel_MsgType_MsgType_MIN;
  static const MsgType MsgType_MAX =
    Backchannel_MsgType_MsgType_MAX;
  static const int MsgType_ARRAYSIZE =
    Backchannel_MsgType_MsgType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  MsgType_descriptor() {
    return Backchannel_MsgType_descriptor();
  }
  static inline const ::std::string& MsgType_Name(MsgType value) {
    return Backchannel_MsgType_Name(value);
  }
  static inline bool MsgType_Parse(const ::std::string& name,
      MsgType* value) {
    return Backchannel_MsgType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional string LogErrMsg = 2;
  bool has_logerrmsg() const;
  void clear_logerrmsg();
  static const int kLogErrMsgFieldNumber = 2;
  const ::std::string& logerrmsg() const;
  void set_logerrmsg(const ::std::string& value);
  #if LANG_CXX11
  void set_logerrmsg(::std::string&& value);
  #endif
  void set_logerrmsg(const char* value);
  void set_logerrmsg(const char* value, size_t size);
  ::std::string* mutable_logerrmsg();
  ::std::string* release_logerrmsg();
  void set_allocated_logerrmsg(::std::string* logerrmsg);

  // required .Backchannel.MsgType type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::Backchannel_MsgType type() const;
  void set_type(::Backchannel_MsgType value);

  // @@protoc_insertion_point(class_scope:Backchannel)
 private:
  void set_has_type();
  void clear_has_type();
  void set_has_logerrmsg();
  void clear_has_logerrmsg();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr logerrmsg_;
  int type_;
  friend struct protobuf_backchannel_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Backchannel

// required .Backchannel.MsgType type = 1;
inline bool Backchannel::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Backchannel::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Backchannel::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Backchannel::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::Backchannel_MsgType Backchannel::type() const {
  // @@protoc_insertion_point(field_get:Backchannel.type)
  return static_cast< ::Backchannel_MsgType >(type_);
}
inline void Backchannel::set_type(::Backchannel_MsgType value) {
  assert(::Backchannel_MsgType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:Backchannel.type)
}

// optional string LogErrMsg = 2;
inline bool Backchannel::has_logerrmsg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Backchannel::set_has_logerrmsg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Backchannel::clear_has_logerrmsg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Backchannel::clear_logerrmsg() {
  logerrmsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_logerrmsg();
}
inline const ::std::string& Backchannel::logerrmsg() const {
  // @@protoc_insertion_point(field_get:Backchannel.LogErrMsg)
  return logerrmsg_.GetNoArena();
}
inline void Backchannel::set_logerrmsg(const ::std::string& value) {
  set_has_logerrmsg();
  logerrmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Backchannel.LogErrMsg)
}
#if LANG_CXX11
inline void Backchannel::set_logerrmsg(::std::string&& value) {
  set_has_logerrmsg();
  logerrmsg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Backchannel.LogErrMsg)
}
#endif
inline void Backchannel::set_logerrmsg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_logerrmsg();
  logerrmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Backchannel.LogErrMsg)
}
inline void Backchannel::set_logerrmsg(const char* value, size_t size) {
  set_has_logerrmsg();
  logerrmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Backchannel.LogErrMsg)
}
inline ::std::string* Backchannel::mutable_logerrmsg() {
  set_has_logerrmsg();
  // @@protoc_insertion_point(field_mutable:Backchannel.LogErrMsg)
  return logerrmsg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Backchannel::release_logerrmsg() {
  // @@protoc_insertion_point(field_release:Backchannel.LogErrMsg)
  clear_has_logerrmsg();
  return logerrmsg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Backchannel::set_allocated_logerrmsg(::std::string* logerrmsg) {
  if (logerrmsg != NULL) {
    set_has_logerrmsg();
  } else {
    clear_has_logerrmsg();
  }
  logerrmsg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), logerrmsg);
  // @@protoc_insertion_point(field_set_allocated:Backchannel.LogErrMsg)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Backchannel_MsgType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Backchannel_MsgType>() {
  return ::Backchannel_MsgType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_backchannel_2eproto__INCLUDED
